GITHUB_ORG: team19hackathon2021
SITE_NAME: "serratus-api"
SITE_SERVICES:
  - SITE_NAME: "serratus-api"
    SITE_SRC: "{{ lookup('env', 'HOME') }}/.local/src/serratus-api"
LANGUAGE_NAME: "enUS"
SITE_JAVA_PACKAGE: io.serratus.api
SITE_PORT: 12080
AUTH_REALM: TEAM19
AUTH_RESOURCE: team19
AUTH_SECRET: 0518f65a-f86d-42e8-ad65-00f46920443d
AUTH_URL: https://sso.computate.org/auth
AUTH_TOKEN_URI: /auth/realms/COMPUTATE.ORG/protocol/openid-connect/token
AUTH_HOST_NAME: sso.computate.org
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_ROLES_ADMIN: [ 'SiteAdmin' ]
AUTH_ROLES_REQUIRED_SiteUser: [ 'SiteAdmin' ]
AUTH_ROLES_REQUIRED_SequenceRun: [ 'SiteAdmin' ]
AUTH_ROLES_REQUIRED_BioSample: [ 'SiteAdmin' ]
AUTH_ROLES_REQUIRED_Taxonomy: [ 'SiteAdmin' ]
JDBC_DATABASE: "serratus"
JDBC_USERNAME: "serratus"
